

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HelpDesk
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HelpDeskEntities : DbContext
{
    public HelpDeskEntities()
        : base("name=HelpDeskEntities")
    {

    }

        private static HelpDeskEntities _context;
        public static HelpDeskEntities GetContext()
        {
            if (_context == null) _context = new HelpDeskEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Обращение> Обращение { get; set; }

    public virtual DbSet<Пользователь> Пользователь { get; set; }

    public virtual DbSet<Тип_пользователя> Тип_пользователя { get; set; }

    public virtual DbSet<Услуги> Услуги { get; set; }

}

}

